#! /bin/sh

sxhkd &
compton --config /home/User/.config/compton/compton.conf &
wmname LG3D &

#Background
feh --bg-fill /home/User/Descargas/photo.png

#Polybar
~/.config/polybar/launch.sh &

bspc config pointer_modifier mod1
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Example
#bspc rule -a Gimp desktop='^8' state=floating follow=on
